name: olisenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - dagster==1.9.13
      - dagster-webserver==1.9.13
      - dagster-dbt==0.25.13
      - dbt-bigquery==1.9.2
      - dbt-core==1.9.6
      - google-cloud-bigquery
      - google-cloud-storage
      - pybigquery
      - sqlalchemy
      - pandas
      - great-expectations
      - meltano==3.7.8
      - python-dotenv==1.1.0
      - streamlit
      - plotly
      - numpy
      - google-auth
      - google-auth-oauthlib
      - pyarrow
      - toml
