name: olisenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - dagster==1.8.11
      - dagster-webserver==1.8.11
      - dagster-dbt==0.24.11
      - dbt-bigquery==1.8.2
      - google-cloud-bigquery
      - google-cloud-storage
      - pybigquery
      - sqlalchemy
      - pandas
      - great-expectations
      - meltano
