
name: "md2_project_olis"
version: "1.0.0"
profile: "md2_project_olis"
config-version: 2

model-paths: ["models"]
target-path: "target"
clean-targets: ["target"]

models:
  md2_project_olis:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
