
name: "md2_project_olis"
profile: "md2_project_olis"
version: "1.0.0"
config-version: 2

model-paths: ["models"]
target-path: "target"
clean-targets: ["target"]
snapshot-paths: ["snapshots"]
macro-paths: ["macros"]

flags:
  require_explicit_package_overrides_for_builtin_materializations: false

models:
  md2_project_olis:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
      # Dimension tables
      dimensions:
        +materialized: incremental
        +incremental_strategy: merge
        +on_schema_change: sync_all_columns
        +schema: marts
        
      # Fact tables  
      facts:
        +materialized: incremental
        +incremental_strategy: merge
        +on_schema_change: sync_all_columns
        +schema: marts

snapshots:
  md2_project_olis:
    +target_schema: snapshots
    
# Configure seeds
seeds:
  md2_project_olis:
    +schema: seed
    brazil_state_regions:
      +column_types:
        state_code: string
        state_name: string
        region: string
        economic_zone: string
