
name: "md2_project_olis"
version: "1.0.0"
profile: "md2_project_olis"
config-version: 2

model-paths: ["models"]
target-path: "target"
clean-targets: ["target"]

models:
  md2_project_olis:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
      # Dimension tables
      dimensions:
        +materialized: table
        +schema: marts
        
      # Fact tables  
      facts:
        +materialized: table
        +schema: marts

# Configure seeds
seeds:
  md2_project_olis:
    +schema: seed
    brazil_state_regions:
      +column_types:
        state_code: string
        state_name: string
        region: string
        economic_zone: string