
md2_project_olis:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('PROJECT_ID') }}"
      dataset: "{{ env_var('STAGING_DATASET_NAME') }}"
      location: US
      threads: 1
      keyfile: "{{ env_var('CREDENTIALS_PATH') }}"
