version: 2

sources:
  - name: olis_raw_dataset
    schema: olis_raw_dataset
    tables:
      - name: orders
      - name: customers
      - name: order_items
      - name: products
      - name: payments
