version: 2

sources:
  - name: raw
    schema: "{{ env_var('RAW_DATASET_NAME') }}"
    tables:
      - name: orders
      - name: customers
      - name: order_items
      - name: products
      - name: payments
