version: 1
default_environment: dev
project_id: md2_project_olis
environments:
- name: dev
- name: staging
- name: prod
plugins:
  extractors:
  - name: tap-csv
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-csv.git
    config:
      files:
      - entity: geolocation
        path: data/geolocation.csv
        keys: [geolocation_zip_code_prefix]
      - entity: orders
        path: data/orders.csv
        keys: [order_id]
      - entity: customers
        path: data/customers.csv
        keys: [customer_id]
      - entity: order_items
        path: data/order_items.csv
        keys: [order_id, order_item_id]
      - entity: products
        path: data/products.csv
        keys: [product_id]
      - entity: payments
        path: data/payments.csv
        keys: [order_id, payment_sequential]
      - entity: order_reviews
        path: data/order_reviews.csv
        keys: [review_id]
      - entity: sellers
        path: data/sellers.csv
        keys: [seller_id]
      - entity: product_category_name_translation
        path: data/product_category_name_translation.csv
        keys: [product_category_name]

  loaders:
  - name: target-bigquery
    variant: z3z1ma
    pip_url: git+https://github.com/z3z1ma/target-bigquery.git
    config:
      project: $PROJECT_ID
      dataset: $RAW_DATASET_NAME
      method: batch_job
      location: US
      credentials_path: $CREDENTIALS_PATH
      denormalized: true
      add_metadata_columns: false
      batch_size: 100000
      timeout: 1200
